config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from rest_framework import routers, serializers, viewsets

from evention.users.views import UserViewSet
from evention.events.views import EventViewSet, IgnoredEventViewSet, LikesViewSet, LikedCityViewSet, HomepageMediaViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'events', EventViewSet)
router.register(r'ignored-events', IgnoredEventViewSet)
router.register(r'likes', LikesViewSet, 'likes')
router.register(r'liked-cities', LikedCityViewSet)
router.register(r'homepage-videos', HomepageMediaViewSet, 'homepage-media')

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("evention.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Events
    url(r'^events/', include('evention.events.urls', namespace="events")),

    # REST framework
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(router.urls, namespace='api')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

evention/events/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.find_events, name="find_events"),
    url(r'discover-artists/$', views.find_bands, name="find_bands"),
    url(r'discover-sports/$', views.find_sports, name="find_sports"),
    url(r'cities/$', views.find_cities, name="find_cities")
]

evention/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

evention/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail import ImageField


# Extra functions, can be used by any of these models
def upload_to(instance, filename):
    return datetime.utcnow().strftime("%Y%m%d%H%M%S%f")[:-3] + "/" + filename


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    picture = ImageField(_("Profile Picture"), upload_to=upload_to, blank=True)

    def __str__(self):
        if self.name != '':
            return self.name
        else:
            return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

evention/events/views.py
import random
import datetime

from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from rest_framework import viewsets
from rest_framework import filters
from rest_framework.response import Response
from rest_framework.exceptions import APIException, PermissionDenied, NotFound

from .models import Event, IgnoredEvent, Likes, Performer, City, LikedCity, HomepageMedia
from .serializers import EventSerializer, IgnoredEventSerializer, LikesSerializer, \
                         LikedCitySerializer, HomepageMediaSerializer


# Django views
@login_required()
def find_events(request):
    return render(request, "events/find_events.html", {})


@login_required()
def find_bands(request):
    return render(request, "events/find_bands.html", {})


@login_required()
def find_sports(request):
    return render(request, "events/find_sports.html", {})


@login_required()
def find_cities(request):
    return render(request, "events/find_cities.html", {})


# REST framework
class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('performer', 'venue_name', 'city', 'country',
                     'latitude', 'longitude', 'start_time')

    def get_queryset(self):
        user = self.request.user
        user_likes = Likes.objects.filter(owner=user)
        performers = list()
        for like in user_likes:
            if like.liked:
                performers.append(like.performer)
        today = datetime.datetime.today()
        return Event.objects.filter(performer__in=performers).filter(Q(start_time__gte=today)).order_by('start_time')

    def create(self, request, *args, **kwargs):
        raise PermissionDenied("Creating and updating events is not yet supported through the API")

    def update(self, request, *args, **kwargs):
        raise PermissionDenied("Creating and updating events is not yet supported through the API")


class IgnoredEventViewSet(viewsets.ModelViewSet):
    queryset = IgnoredEvent.objects.all()
    serializer_class = IgnoredEventSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('ignored', 'event', 'since')

    def get_queryset(self):
        user = self.request.user
        return IgnoredEvent.objects.filter(owner=user)

    def update(self, request, *args, **kwargs):
        try:
            ignored_event = IgnoredEvent.objects.get(event__id=request.data['id'],
                                                     owner=request.user)
            print(ignored_event)
        except IgnoredEvent.DoesNotExist:
            event = Event.objects.get(id=request.data['id'])
            ignored_event = IgnoredEvent(event=event, owner=request.user)

        if request.data['ignored'] == 'true':
            ignored_event.ignored = True
            response_string = 'Event successfully ignored'
        elif request.data['ignored'] == 'false':
            ignored_event.ignored = False
            response_string = 'Event successfully unignored'
        else:
            response_string = 'Cannot ignore or unignore this event. ' \
                              'Make sure to set \'ignored\' to either true or false'

        ignored_event.save()
        return Response({'status': response_string, 'id': ignored_event.id})


class LikesViewSet(viewsets.ModelViewSet):
    queryset = Likes.objects.all()
    serializer_class = LikesSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('owner', 'liked', 'performer', 'since')

    def get_queryset(self):
        """
        This view should return a list of all the likes
        for the currently authenticated user.
        """
        user = self.request.user
        return Likes.objects.filter(owner=user)

    # Handles PUT requests.
    def update(self, request, *args, **kwargs):
        try:  # In case of un-liking an existing like, or re-liking an old like.
            like = Likes.objects.get(id=request.data['id'])

        except Likes.DoesNotExist:  # Else create a new like
            try:
                performer = Performer.objects.get(name=request.data['performer'])
            except Performer.DoesNotExist:
                performer = Performer(name=request.data['performer'], type='artist', image=request.data['image'])
                performer.save()

            like = Likes(owner=request.user, performer=performer)

        if like.owner != request.user:
            raise PermissionDenied("Adding likes for different users not supported.")

        if request.data['liked'] == 'true':
            like.liked = True
            response_string = 'Performer successfully liked'
        elif request.data['liked'] == 'false':
            like.liked = False
            response_string = 'Performer successfully unliked'
        else:
            response_string = 'Cannot like or unlike this performer. Make sure to set \'liked\' to either true or false'
        like.save()

        return Response({'status': response_string, 'id': like.id})


class LikedCityViewSet(viewsets.ModelViewSet):
    queryset = LikedCity.objects.all()
    serializer_class = LikedCitySerializer

    def get_queryset(self):
        """
        This view should return a list of all the liked cities
        for the currently authenticated user.
        """
        user = self.request.user
        return LikedCity.objects.filter(owner=user)

    # Handles PUT requests.
    def update(self, request, *args, **kwargs):
        try:  # In case of un-liking an existing city, or re-liking an old like.
            liked_city = LikedCity.objects.get(id=request.data['id'])

        except LikedCity.DoesNotExist:  # Else create a new like
            liked_city = LikedCity(owner=request.user)
            try:
                city = City.objects.get(code=request.data['code'])
            except City.DoesNotExist:
                city = City(code=request.data['code'],
                            city=request.data['city'],
                            region=request.data['region'],
                            country=request.data['country'],
                            latitude=request.data['latitude'],
                            longitude=request.data['longitude'])
                city.save()
            liked_city.city = city

        if liked_city.owner != request.user:
            raise PermissionDenied("Adding likes for different users not supported.")

        if request.data['liked'] == 'true':
            liked_city.liked = True
            response_string = 'City successfully liked'
        elif request.data['liked'] == 'false':
            liked_city.liked = False
            response_string = 'City successfully unliked'
        else:
            response_string = 'Cannot like or unlike this city. Make sure to set \'liked\' to either true or false'
        liked_city.save()

        return Response({'status': response_string, 'id': liked_city.id})


class HomepageMediaViewSet(viewsets.ModelViewSet):
    queryset = HomepageMedia.objects.all()
    serializer_class = HomepageMediaSerializer

    # Currently, returns a randomized ordering of all of the homepage videos.
    def get_queryset(self):
        try:
            return HomepageMedia.objects.order_by('?')
        except IndexError:
            raise NotFound("Sorry, there's not any media added yet.")

evention/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import viewsets

from .models import User
from .serializers import UserSerializer
from evention.events.models import Likes, LikedCity


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['likes'] = Likes.objects.filter(owner=self.request.user, liked=True)
        context['cities'] = LikedCity.objects.filter(owner=self.request.user, liked=True)
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'picture']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


# REST framework
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user

evention/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Evention{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    {% endblock %}

     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Evention</a>
        </div>

        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            {% if request.user.is_authenticated %}
              <li><a href="{% url 'events:find_bands' %}">Artists</a></li>
              <li><a href="{% url 'events:find_events' %}">Events</a></li>
              <li><a href="{% url 'events:find_cities' %}">Cities</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              {% if debug and request.user.is_superuser %}
                <li><a href="{% url 'api:api-root' %}">API Reference</a></li>
              {% endif %}
              {% if request.user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
              {% endif %}
              <li><a href="{% url 'users:detail' request.user.username  %}">Account</a></li>
              <li><a href="{% url 'account_logout' %}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'account_login' %}">Log In</a></li>
              <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}
      {% block content %}{% endblock content %}
    </div> <!-- /container -->
    <div class="navbar navbar-default navbar-fixed-bottom hidden-xs">
      <div class="container">
        <p class="navbar-text">A site (in progress) by <a class="navbar-link" href="http://ericzaporzan.com" target="_blank">Eric Zaporzan</a>.  Built with Django, Knockout, Bootstrap, and more. <a href="{% url 'about' %}" class="navbar-link">Additional info</a>. <a href="mailto:me@ericzaporzan.com" class="navbar-link">E-mail me</a>.</p>
        <div class="navbar-right">
          {% block footer-branding %}{% endblock %}
        </div>
      </div>
    </div>

    {% block modal %}{% endblock modal %}

    <script>
    $(document).ready(function () {
      $('[data-toggle="tooltip"]').tooltip();
    });
    </script>

    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

      <!-- Moment.js - datetime parsing -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>

      <!-- knockout files go in this block, as needed, to save on processing time. -->
      {% block knockout %}{% endblock %}

    {% endblock javascript %}
  </body>
</html>